# Generated by Django 5.2.15 on 2026-06-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localizationguide',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='localizationguide',
            name='target_country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
