# Generated by Django 5.2.15 on 2026-06-18 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_name', models.CharField(max_length=30)),
                ('age', models.CharField(blank=True, max_length=10)),
                ('role', models.CharField(blank=True, max_length=5)),
                ('gender', models.CharField(blank=True, max_length=5)),
                ('relationships', models.CharField(blank=True, max_length=500)),
                ('appearance', models.CharField(blank=True, max_length=300)),
                ('detail_setting', models.CharField(blank=True, max_length=1000)),
                ('source', models.CharField(choices=[('MANUAL', '수동 입력'), ('AI', 'AI 추출')], default='MANUAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='works.work')),
            ],
        ),
    ]
