# Generated by Django 5.2.15 on 2026-06-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_relation_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='relation',
        ),
    ]
