# Generated by Django 5.2.15 on 2026-06-17 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covers', '0001_initial'),
        ('works', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('target_country', models.CharField(choices=[('US', '미국/영어권'), ('CN', '중국'), ('JP', '일본'), ('TH', '태국')], max_length=2)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('synopsis_snapshot', models.TextField()),
                ('synopsis_hash', models.CharField(max_length=64)),
                ('user_prompt', models.CharField(blank=True, max_length=500)),
                ('final_prompt', models.TextField(blank=True)),
                ('image_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('SUCCESS', '성공'), ('FAILED', '실패'), ('BLOCKED', '차단')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('model_name', models.CharField(default='gpt-image-2', max_length=50)),
                ('prompt_version', models.CharField(default='cover_v1', max_length=50)),
                ('credit_amount', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_images', to='works.work')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['work', 'target_country', 'is_deleted'], name='covers_cove_work_id_93bdc7_idx'), models.Index(fields=['created_by', 'is_deleted'], name='covers_cove_created_994ce2_idx')],
            },
        ),
    ]
