CHARACTER_LIMIT_PER_WORK = 20

NAME_MAX_LENGTH = 30
AGE_MAX_LENGTH = 10
ROLE_MAX_LENGTH = 5
GENDER_MAX_LENGTH = 5
RELATION_MAX_LENGTH = 500
APPEARANCE_MAX_LENGTH = 300
DETAIL_MAX_LENGTH = 1000

ROLE_ORDER = {
    "주인공": 0,
    "주요 인물": 1,
    "주요인물": 1,
    "조연": 2,
    "단역": 3,
}

