COVER_IMAGE_LIMIT_PER_WORK = 5
RELATION_MAP_LIMIT_PER_WORK = 3
RELATION_CHARACTER_LIMIT = 10
EXTRA_PROMPT_MAX_LENGTH = 500

AI_IMAGE_NOTICE = "AI로 생성된 이미지입니다."

TARGET_COUNTRY_CHOICES = (
    ("JP", "일본"),
    ("CN", "중국"),
    ("US", "미국"),
    ("TH", "태국"),
)

