# Generated by Django 5.2.15 on 2026-06-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='translationresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='translationresult',
            name='annotation_can',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='translationresult',
            name='glossary_can',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='translationresult',
            name='inspection_report',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='translationresult',
            name='original_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='translationresult',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='translationresult',
            name='version_no',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_type',
            field=models.CharField(choices=[('USER', '사용자'), ('ASSISTANT', '챗봇')], max_length=20),
        ),
        migrations.AlterField(
            model_name='translationresult',
            name='status',
            field=models.CharField(choices=[('DRAFT', '작성중'), ('DONE', '완료'), ('BLOCKED', '안전성 차단')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='translationresult',
            name='target_language',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='translationresult',
            name='translated_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='translationresult',
            unique_together={('episode', 'target_country', 'version_no')},
        ),
    ]
